### ISSUE TITLE
Refactoring: Resolve clash between `s` for "state" and `s` for "stream instance"

### ISSUE THREAD

**Issue by cognivore** [yatima-inc/Megaparsec.lean#10]
# Why?

As we implement more and more meaningful functions and implementations, `s` quickly becomes used to denote `state` variables.
Notation `s` for "stream instance" clashes with it, making the code less readable at a glance.

# How? 

 - [ ] Pick what to rename: state, stream instance, or both
 - [ ] Do a renaming and make sure that everything was renamed

**Comment by cognivore** [comment]
@arthurpaulino this will make a clash between `StateT` state and `MonadParsec` state.

**Comment by DanielRrr** [comment]
I would be with `s` for `state` and `stream` for instance arguments

**Comment by ixahedron** [comment]
Closed as done (a long time ago), we're going with `℘` for source/stream.

**Comment by cognivore** [comment]
We have appropriated the symbol for [Weirstrass elliptic function](https://en.wikipedia.org/wiki/Weierstrass_elliptic_function).
