### ISSUE TITLE
Refactoring: Rename tokensToChunk and chunkToTokens to avoid confusing word "tokens"

### ISSUE THREAD

**Issue by cognivore** [yatima-inc/Megaparsec.lean#12]
# Why?

Chunks are `stream.Tokens` by definition. `Tokens` in functions `tokensToChunk` and `chunkToTokens` are `List Token`. It creates a cognitive contradiction.

# How?

 - [ ] Pick a better way to refer to the concept of "List of Token" in the function names
 - [ ] Rename it in the typeclass definition, all the instances and usages

**Comment by ixahedron** [comment]
Closed as done; we've deviated from reference a long time ago with Iterable.
