### ISSUE TITLE
Clarity: Less verbose NEList

### ISSUE THREAD

**Issue by cognivore** [yatima-inc/Megaparsec.lean#47]
# Why?

https://zulip.yatima.io/#narrow/stream/24-yatima-tools/topic/.5BYatimaStdLib.2Elean.5D.20chat/near/44221

# How?

https://zulip.yatima.io/#narrow/stream/24-yatima-tools/topic/.5BYatimaStdLib.2Elean.5D.20chat/near/44221

**Comment by ixahedron** [comment]
`NEList` was changed a handful of times, the changes most recently included getting rid of `NEList.mk` in Megaparsec, so I'm closing it.
